package car_rental;


import car_rental.login_page;
import com.github.lgooddatepicker.components.DateTimePicker;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalTime;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;
import java.lang.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.lang.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ankur
 */
public class Book_page extends javax.swing.JFrame {

    public Connection cn;
public Statement st;
int carid;
int cid;
String amt2;
String bookid;



    /**
     * Creates new form Book
     */
    public Book_page() {
        initComponents();
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental ","root","07121998");
             st = cn.createStatement();
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
    }
    
    
    public Book_page(int carid1) 
    {
        initComponents();
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental ","root","07121998");
             st = cn.createStatement();
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
        System.out.println(carid1);
        carid = carid1;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jButton1 = new javax.swing.JButton();
        dateTimePicker2 = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 102, 1920, 10);

        dateTimePicker1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(dateTimePicker1);
        dateTimePicker1.setBounds(60, 410, 310, 40);

        jButton1.setText("Estimate");
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(890, 510, 140, 50);

        dateTimePicker2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(dateTimePicker2);
        dateTimePicker2.setBounds(60, 230, 320, 40);

        jLabel1.setText("Booking");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 20, 270, 70);

        jLabel2.setText("Pickup");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 150, 120, 40);

        jLabel3.setText("Return");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 340, 100, 30);

        jLabel4.setText("Email:");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1050, 180, 90, 60);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(1170, 190, 220, 40);

        jLabel5.setText("Estimated Amount :");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(600, 740, 280, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(860, 750, 170, 40);

        jButton2.setText("OK");
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 840, 100, 40);

        jButton3.setText("Cancel");
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(890, 840, 100, 40);

        jButton7.setText("Back");
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(40, 30, 130, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Pictures\\Project\\vdVU8C.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        LocalDate dt1,dt2,dt;
        dt1 = dateTimePicker1.datePicker.getDate();
        LocalTime tm1,tm2;
        tm1= dateTimePicker1.timePicker.getTime();
        dt2 = dateTimePicker2.datePicker.getDate();
        tm2= dateTimePicker2.timePicker.getTime();
        
        String dtm1=dt2.toString()+" "+tm2.toString();
        System.out.println(dtm1);
        String dtm2=dt1.toString()+" "+tm1.toString();
        System.out.println(dtm2);
        System.out.println(carid);
        
        
       
        try{
    
            String sql1 = "select c_id from customer where email = '" + jTextField1.getText() + "'"; 
            ResultSet res1 = st.executeQuery(sql1);
            
             if(res1.next())
            {
                
            cid = res1.getInt("C_id");
               
            }
             
             else {
                 JOptionPane.showMessageDialog(null,"Invalid User");
                 Book_page fp = new Book_page(carid);
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             }
             
             
             String sql5 = "select book_id from booking where c_id ='" + cid + "'"; 
            ResultSet res5 = st.executeQuery(sql5);
            
             if(res5.next())
             {
                 
                JOptionPane.showMessageDialog(null,"Already Booked a car with this email");
                 location_page fp = new location_page();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             }
             
             else
             {
             String sql2 = "insert into booking values(DEFAULT,'" + dtm1 + "',DEFAULT,'" + dtm2 + "',DEFAULT,'" + carid + "','" + cid + "')"; 
            int res2= st.executeUpdate(sql2);
             System.out.println(res2);
             
             String sql3 = "call cal_amt('" + cid + "')";
             int res3 = st.executeUpdate(sql3);
             System.out.println(res3);
             
             
             String sql4 = "select amt from booking where c_id = '" + cid + "'"; 
            ResultSet res4 = st.executeQuery(sql4);
            
             if(res4.next())
            {
             String amt1 = res4.getString("amt");
            jLabel6.setText("Rs. "+amt1);
               
            }
             }
        }
        catch (SQLException ex) {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
        
      
              
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            
            String sql6 = "select book_id,amt from booking where c_id = '" + cid + "'"; 
            ResultSet res6 = st.executeQuery(sql6);
            
             if(res6.next())
            {
             amt2 = res6.getString("amt");
             bookid = res6.getString("book_id");
               
            }
             
            String sql7 = "insert into billing values(DEFAULT,DEFAULT,'" + amt2 + "',DEFAULT,DEFAULT,DEFAULT,DEFAULT,'" + bookid + "')"; 
            int res7= st.executeUpdate(sql7);
             System.out.println(res7);
             JOptionPane.showMessageDialog(null,"Booking Succesful");
             location_page fp = new location_page();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             
        }
        
        catch (SQLException ex) {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        try
        {
            
            String sql7 = "delete from booking where c_id ='" + cid + "'";
        
        int res7 = st.executeUpdate(sql7);
             System.out.println(res7);
             location_page fp = new location_page();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
             
        }
             catch (SQLException ex) {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        location_page fp = new location_page();
        fp.setVisible(true);
        fp.pack();
        fp.setLocationRelativeTo(null);
        fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
