/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rental;


import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/**
 *
 * @author ankur
 */
public class location_page extends javax.swing.JFrame {

    Connection cn;
    Statement st,st1,st2;
    ResultSet rs;
    public String locid;
    String s1 = "jayanagar";
        String s2 = "Indiranagar";
        String s3 = "banashankari";
        public String cid,bookid;
        
        
    /**
     * Creates new form car_page
     */
    
    
    public location_page() {
        initComponents();
        
          try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental ","root","07121998");
             st = cn.createStatement();
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
         
    }
    
    public location_page(String cid,String fname) {
        initComponents();
           try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental ","root","07121998");
             st = cn.createStatement();
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
        jLabel1.setText(fname);
        System.out.println(cid+"  "+fname);
        System.out.println("HERE");
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        car_rentalPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("car_rentalPU").createEntityManager();
        carQuery = java.beans.Beans.isDesignTime() ? null : car_rentalPUEntityManager.createQuery("SELECT c FROM Car c");
        carList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carQuery.getResultList();
        carQuery1 = java.beans.Beans.isDesignTime() ? null : car_rentalPUEntityManager.createQuery("SELECT c FROM Car c");
        carList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carQuery1.getResultList();
        carQuery2 = java.beans.Beans.isDesignTime() ? null : car_rentalPUEntityManager.createQuery("SELECT c FROM Car c");
        carList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carQuery2.getResultList();
        carQuery3 = java.beans.Beans.isDesignTime() ? null : car_rentalPUEntityManager.createQuery("SELECT c FROM Car c");
        carList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carQuery3.getResultList();
        carQuery4 = java.beans.Beans.isDesignTime() ? null : car_rentalPUEntityManager.createQuery("SELECT c FROM Car c");
        carList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : carQuery4.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 210, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("4Wheels.com");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1590, 30, 310, 50);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 110, 1920, 20);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Location", "Jayanagar", "Indiranagar", "Banashankari" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(810, 180, 280, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 270, 130, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 30, 260, 60);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Logout");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(1620, 680, 130, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bill Details:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 760, 190, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 780, 100, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(400, 780, 180, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Late Fee:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(730, 800, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tax:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(730, 900, 60, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Amount:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1170, 840, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(860, 810, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(800, 910, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1360, 840, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Check");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 880, 120, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Pictures\\Project\\9XNMK1U.jpg")); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 6, 1920, 1080);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        
           String text = (String)jComboBox1.getSelectedItem();
           
           try{
            String sql = "Select * from location where loc_name = '" + jComboBox1.getSelectedItem() + "'";
            rs = st.executeQuery(sql);
            
            if(rs.next())
            {
               
              locid= rs.getString("loc_id");
            }
            else{
                JOptionPane.showMessageDialog(null,"Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(text.equalsIgnoreCase(s1))
        {
            
            car_page fp = new car_page();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        
        else if(text.equalsIgnoreCase(s2))
        {
            car_page1 fp = new car_page1();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        
        else if(text.equalsIgnoreCase(s3))
        {
            car_page2 fp = new car_page2();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
           
           
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        login_page fp = new login_page();
        fp.setVisible(true);
        fp.pack();
        fp.setLocationRelativeTo(null);
        fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        try
        {
            String q1 = "select c_id from customer where email ='" + jTextField1.getText() + "'";
            ResultSet res = st.executeQuery(q1); 
            
            if(res.next())
            {
                cid = res.getString("c_id");
                System.out.println(cid);
            }
            else
            {
            }
        }
                catch (SQLException ex) {
            Logger.getLogger(location_page.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try
           {
               
                    String q2 = "select * from booking where c_id = '" + cid + "'";
                     ResultSet res1 = st.executeQuery(q2);
                
                if(res1.next())
                {
                    bookid = res1.getString(1);
                    System.out.println(bookid);
                }
                else
                {
                }
                
                 } catch (SQLException ex) {
            Logger.getLogger(location_page.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                    try
                    {
                        String q3 = "select * from billing where book_id = '" + bookid + "'";
                    
                    ResultSet res2 = st.executeQuery(q3);

                    if(res2.next())
                    {

                String latefee = res2.getString("Late_fee");
                String tax = res2.getString("Tax");
                String totamt = res2.getString("Total_amt");


                jLabel9.setText("Rs. "+latefee);
                jLabel10.setText("Rs. "+tax);
                jLabel11.setText("Rs. "+totamt);
                    }
                    }
                    catch (SQLException ex) {
            Logger.getLogger(location_page.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                    
       
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new location_page().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<car_rental.Car> carList;
    private java.util.List<car_rental.Car> carList1;
    private java.util.List<car_rental.Car> carList2;
    private java.util.List<car_rental.Car> carList3;
    private java.util.List<car_rental.Car> carList4;
    private javax.persistence.Query carQuery;
    private javax.persistence.Query carQuery1;
    private javax.persistence.Query carQuery2;
    private javax.persistence.Query carQuery3;
    private javax.persistence.Query carQuery4;
    private javax.persistence.EntityManager car_rentalPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
