/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_rental;


import java.sql.*;
import java.sql.ResultSet;
import javax.swing.JFrame;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.lang.*;


public class login_page extends javax.swing.JFrame {
    
public Connection cn;
public Statement st;

public login_page(){
    initComponents();
    this.setLocationRelativeTo(null);
    try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental ","root","07121998");
             st = cn.createStatement();
             
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Connected");
        }
    
        
        
}

    

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTextField1 = new javax.swing.JTextField();
        JPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 204, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("4Wheels.com");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(1540, 20, 360, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Email");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(690, 360, 120, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Password");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(690, 470, 150, 34);

        JTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(JTextField1);
        JTextField1.setBounds(880, 360, 280, 40);

        JPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPasswordField2ActionPerformed(evt);
            }
        });
        jPanel3.add(JPasswordField2);
        JPasswordField2.setBounds(880, 470, 280, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("Login");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(860, 600, 170, 60);

        jButton6.setBackground(new java.awt.Color(153, 153, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(70, 60, 120, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ankur\\OneDrive\\Pictures\\Project\\sdf.jpg")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(1, -4, 1920, 1090);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordField2ActionPerformed
        
        
    }//GEN-LAST:event_JPasswordField2ActionPerformed

    private void JTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField1ActionPerformed
        
        
    }//GEN-LAST:event_JTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       
       
        try{
            String sql = "Select * from customer where email = '" + JTextField1.getText() + "' and Password ='" + String.valueOf(JPasswordField2.getPassword()) + "'";
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next())
            {
                
                JOptionPane.showMessageDialog(null,"Logged in");
                 String cid = rs.getString("c_id");
                 String fname = rs.getString("fname");
                 
                  
                
               
                location_page fp = new location_page(cid,fname);
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid User");
            }
        } catch (SQLException ex) {
            Logger.getLogger(login_page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       
        
        
        Front_page fp = new Front_page();
            fp.setVisible(true);
            fp.pack();
            fp.setLocationRelativeTo(null);
            fp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            
            
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPasswordField2;
    private javax.swing.JTextField JTextField1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}

